{% set name = "pixiedust" %}
{% set version = "1.1.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3d37ee70a2b1491ff2ae479fe1526841357a9cb962eafe835686231a98dd8da2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - mpld3
    - jupyter
    - lxml
    - geojson
    - astunparse
    - markdown
    - colour
    - requests
    - numpy
    - pandas
    - matplotlib-base
    - bokeh

test:
  imports:
    # pixiedust serious hacks to ipython, not sure it is quite a good test
    # this test could be fragile
    - pixiedust

about:
  home: https://github.com/pixiedust/pixiedust
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: PixieDust is a productivity tool for Python or Scala notebooks, which lets a developer encapsulate business logic into something easy for your customers to consume.

extra:
  recipe-maintainers:
    - hmaarrfk
