{% set name = "pixiedust" %}
{% set version = "1.1.18" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d2252c1fdb58ac0cd754bcd4c42f389864a4eacaba5ee2719552c1bcc2663662

build:
  # cannot be noarch since there is an exe generated at the end.
  number: 2
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - mpld3
    - jupyter
    - lxml
    - geojson
    - astunparse
    - markdown
    - colour
    - requests
    # these aren't directly listed, but they directly import them...
    - numpy
    - pandas
    - matplotlib-base
    - bokeh

test:
  imports:
    # pixiedust serious hacks to ipython, not sure it is quite a good test
    # this test could be fragile
    - pixiedust

about:
  home: https://github.com/pixiedust/pixiedust
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'PixieDust is a productivity tool for Python or Scala notebooks, which lets a developer encapsulate business logic into something easy for your customers to consume.'

extra:
  recipe-maintainers:
    - hmaarrfk
